### ISSUE TITLE
Optimise parks list request.

### ISSUE THREAD

**Issue by joshJarr** [tomwieck/triffids#65]
Currently the parks list requests are ver slow, taking a few seconds to complete. We should address this and look into a solution.

**Comment by joshJarr** [comment]
I did this, https://github.com/tomwieck/triffids/commit/8696ad2164cecc4fb71f2b3e259e2209e1e6de84
Improves things a bit - but still not perfect. Make this can be looked into post MVP

**Comment by fznsakib** [comment]
This is I assume mainly coming from the fact that total_trees and unique_species are each making a call to the API and is mentioned in #61
